//4DPlugin.h
/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : 4d-plugin-pty
 #	author : Eric
 #	2/14/26
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include <string>
#include "C_TEXT.h"
#include "C_LONGINT.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

// --- pty
void PTY_Create(PA_PluginParameters params);
void PTY_Write(PA_PluginParameters params);
void PTY_Read(PA_PluginParameters params);
void PTY_Set_window_size(PA_PluginParameters params);
void PTY_Close(PA_PluginParameters params);
void PTY_Get_status(PA_PluginParameters params);
void PTY_Send_signal(PA_PluginParameters params);
void PTY_List_sessions(PA_PluginParameters params);
